using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using cmsRestApi.Models;
using cmsRestApi.Repository;
using cmsRestApi.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace cmsRestApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class EMailController : ControllerBase
    {
        LabReportVMRepository repository;

        public EMailController(LabReportVMRepository _repository)
        {
            repsitory = _repository;
        }

        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> SendMail( int id )
        {
            var report = await repository.(id);
            var client = new System.Net.Mail.SmtpClient("smtp.gmail.com", 587);
            client.UseDefaultCredentials = false;
            client.EnableSsl = true;
            client.Credentials = new System.Net.NetworkCredential("iclinichealthcarepvtltd@gmail.com", "iclinic09!");
            var mailMessage = new System.Net.Mail.MailMessage();
            mailMessage.From = new System.Net.Mail.MailAddress("iclinichealthcarepvtltd@gmail.com");
            mailMessage.To.Add(exp.EmailId);
            mailMessage.IsBodyHtml = true;
            mailMessage.Body += " <h1 style='color: Red;'><center>IClinic Health Care<center></h1>\n ";
            mailMessage.Body += " <h3><center>Lab Test Report<center></h3>\n ";
            mailMessage.Body += "<hr>";
            mailMessage.Body += "<div style='font-size: 1.2em; font-family:Lucida Console;'>";
            mailMessage.Body += "Pateint Id:" + report.PatientId +"<br>";
            mailMessage.Body += "Pateint name:" + report.PatientName + "<br>";
            mailMessage.Body += "Consulted Doctor: Dr." + report.DoctorName + "<br>";
            mailMessage.Body += "Test Generated By:" + report.StaffName + "<br>";
            mailMessage.Body += "Date Of Appoitment:" + report.DateOfAppointment + "<br>";
            mailMessage.Body += "<hr>";
            mailMessage.Body += "<table><thead><tr><th>Test</th><th>Result</th></tr></thead><tbody><tr>";
            mailMessage.Body += "<td>" + report.TestOneName + "</td>";
            mailMessage.Body += "<td>" + report.ObservedResultOne + "</td> </tr>";
            if (report.TestTwoName != null)
            {
                mailMessage.Body += "<tr>";
                mailMessage.Body += "<td>" + report.TestTwoName + "</td>" ;
                mailMessage.Body += "<td>" + report.ObservedResultTwo + "</td>";
                mailMessage.Body += "<tr>";
            }
            if (report.TestThreeName != null)
            {
                mailMessage.Body += "<tr>";
                mailMessage.Body += "<td>" + report.TestThreeName + "</td>";
                mailMessage.Body += "<td>" + report.ObservedResultThree + "</td>";
                mailMessage.Body += "<tr>";
            }
            mailMessage.Body += "</tr></tbody></table?</div>";
            mailMessage.Body += "<hr> Thank You for visitng IClinic <hr>";
            //mailMessage.Attachments.Add(new System.Net.Mail.Attachment(ModelState, "example.text",""))
            await client.SendMailAsync(mailMessage);
            return Ok();
        }
    }
}

